---
resources:
  - name: concourse-examples
    type: git
    icon: github
    check_every: 168h
    source:
      uri: https://github.com/RajKailas17/concourse-pipeline-automation.git
      branch: main

jobs:
  # update this pipeline before updating child pipelines
  - name: set-self
    public: true
    plan:
      - get: concourse-examples
        trigger: true
      - set_pipeline: self
        file: concourse-examples/concourse-examples/set-pipelines.yml

  - name: set-rendered-pipelines
    public: true
    plan:
      - get: concourse-examples
        trigger: true
        passed: [set-self]
      - task: render-pipelines
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: taylorsilva/carvel-ytt
          inputs:
            - name: concourse-examples
          outputs:
            - name: pipeline
          run:
            path: sh
            args:
              - -cx
              - |
                ytt -f ./concourse-examples/pipelines/templates/simple > hello-world-rendered.yml
                ytt -f ./concourse-examples/pipelines/templates/multiple-files > multi-files-rendered.yml
                mv *.yml ./pipeline/
      - set_pipeline: hello-world-rendered
        file: pipeline/hello-world-rendered.yml
      - set_pipeline: multi-files-rendered
        file: pipeline/multi-files-rendered.yml