---
resources:
- name: source
  type: git
  source: {uri: https://github.com/RajKailas17/concourse-pipeline-automation.git}

jobs:
  - name: configure-self
    plan:
    - get: source
      trigger: true
    - set_pipeline: self
      file: source/pipelines/pipeline.yml

  - name: hello
    plan:
      - get: source
        trigger: true
        passed: [configure-self]
      - task: echo-hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello world!"]

      - task: echo-hello-vault
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args:
              - -exc
              - |
                echo ${MESSAGE}
            params:
            MESSAGE: ((concourse/myteam:testmessage))