---
resources:
  - name: source-code
    type: git
    icon: github
    check_every: 30m
    source:
      uri: https://github.com/RajKailas17/concourse-pipeline-automation.git

jobs:
  - name: set-self
    plan:
    - get: source-code
      trigger: true
    - set_pipeline: self
      file: source-code/pipelines/pipeline.yml

  - name: hello
    plan:
      - get: source-code
        trigger: true
        passed: [set-self]
      - task: echo-hello-world
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: echo
            args: ["Hello world! - 12345"]

      - task: echo-hello-vault
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          run:
            path: sh
            args:
              - -exc
              - |
                echo ${MESSAGE}
            params:
            MESSAGE: ((hello))
  - name: set-rendered-pipelines
    public: true
    plan:
      - get: source-code
        trigger: true
        passed: [set-self]
      - task: render-pipelines
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: taylorsilva/carvel-ytt
          inputs:
            - name: source-code
          outputs:
            - name: pipeline-rendered
          run:
            path: sh
            args:
              - -cx
              - |
                ytt -f ./source-code/pipelines/templates/simple > hello-world-rendered-raj.yml
                ytt -f ./source-code/pipelines/templates/multiple-files > multi-files-rendered-raj.yml
                mv *.yml ./pipeline/
      - set_pipeline: hello-world-rendered-raj
        file: pipeline-rendered/hello-world-rendered-raj.yml
      - set_pipeline: multi-files-rendered-raj
        file: pipeline-rendered/multi-files-rendered-raj.yml