FROM arbourd/concourse-fly:latest

COPY setup-pipeline.sh setup-hello-pipeline.sh
COPY ./pipeline.yml pipeline.yml
RUN chmod +x setup-hello-pipeline.sh

CMD ["./setup-hello-pipeline.sh", "sleep", "infinity"]