jobs:
  - name: worker
    plan:
      - task: wait
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          outputs:
            - name: tags
            - name: context
          run:
            path: /bin/sh
            args:
              - -exc
              - |
                for i in $(seq 20)
                do
                    echo "Attempt #${i}"
                    sleep 10
                    echo "123456789"
                done