resources:

  - name: code
    type: git
    icon: github
    check_every: 168h
    source:
      uri: https://github.com/RajKailas17/concourse-pipeline-automation.git
      branch: main

jobs:
  - name: set-self
    public: true
    plan:
      - get: code
        trigger: true
      - set_pipeline: self
        file: code/pipelines/job-params/set-job-params-pipeline.yml
  - name: set-pipelines
    plan:
      - get: code
        trigger: true
        passed: [ set-self ]
      - set_pipeline: job-params-pipeline
        file: code/pipelines/job-params/job-params-pipeline.yml
        vars:
          GIT_BRANCH: main
          message: Hello world, vars pipeline1
      - set_pipeline: job-params-pipeline-2
        file: code/pipelines/job-params/job-params-pipeline.yml
        var_files:
          - code/pipelines/job-params/var-params.yml
